server:
  port: 8081
  servlet:
    context-path: /api/pleaser/v1
  error:
    whitelabel:
      enabled: false
    include-message: always
  jetty:
    max-http-form-post-size: 10MB
  tomcat:
    max-http-form-post-size: 20MB

#  max-http-post-size: 2000000



springdoc:
  swagger-ui:
    path: /docs

spring:
  jpa:
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: none
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
  web:
    cors:
      allowed-methods: GET,POST,PUT,DELETE,OPTIONS

  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: pleaser-service
            scope: openid, email, roles, ip, userId, web-origins, P_MU_C, profile, objectKeys
            authorization-grant-type: authorization_code
            client-secret: 9ef5d228-8673-4516-acdf-f31c62684f4f
            redirect-uri: http://10.16.113.31:5173/login/oauth2/code/keycloak
        provider:
          keycloak:
            authorization-uri: http://172.16.110.31:8080/auth/realms/TebyanWeb/protocol/openid-connect/auth
            token-uri: http://172.16.110.31:8080/auth/realms/TebyanWeb/protocol/openid-connect/token
            user-info-uri: http://172.16.110.31:8080/auth/realms/TebyanWeb/protocol/openid-connect/userinfo
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/pleasure
    username: root
    password: root


keycloak:
  logout-url: http://172.16.110.31:8080/auth/realms/TebyanWeb/protocol/openId-connect/logout
  login: http://10.16.113.20:8081/oath2/authorization/keycloak
  server: http://172.16.110.31:8080

#debug: true

